---
fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
    libvirt: https://github.com/cirrax/puppet-libvirt.git
    nftables: https://github.com/voxpupuli/puppet-nftables.git
    inifile: https://github.com/puppetlabs/puppetlabs-inifile.git
